"""Initial migration

Revision ID: 6f0ee1fcce1a
Revises: 
Create Date: 2024-02-27 21:10:21.765856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0ee1fcce1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_assigned_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('task_assigned_to_fkey', type_='foreignkey')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('assigned_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_assigned_to_fkey', 'user', ['assigned_to'], ['id'])
        batch_op.create_foreign_key('task_assigned_user_fkey', 'user', ['assigned_user'], ['id'])

    # ### end Alembic commands ###
